/**
 * This class is generated by jOOQ
 */
package com.biblioteca.generatedclasses.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Token extends org.jooq.impl.TableImpl<com.biblioteca.generatedclasses.tables.records.TokenRecord> {

	private static final long serialVersionUID = -1740937406;

	/**
	 * The singleton instance of <code>bibliotecapo.token</code>
	 */
	public static final com.biblioteca.generatedclasses.tables.Token TOKEN = new com.biblioteca.generatedclasses.tables.Token();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.biblioteca.generatedclasses.tables.records.TokenRecord> getRecordType() {
		return com.biblioteca.generatedclasses.tables.records.TokenRecord.class;
	}

	/**
	 * The column <code>bibliotecapo.token.id</code>. 
	 */
	public final org.jooq.TableField<com.biblioteca.generatedclasses.tables.records.TokenRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>bibliotecapo.token.token</code>. 
	 */
	public final org.jooq.TableField<com.biblioteca.generatedclasses.tables.records.TokenRecord, java.lang.String> TOKEN_ = createField("token", org.jooq.impl.SQLDataType.VARCHAR.length(25).nullable(false), this);

	/**
	 * Create a <code>bibliotecapo.token</code> table reference
	 */
	public Token() {
		super("token", com.biblioteca.generatedclasses.Bibliotecapo.BIBLIOTECAPO);
	}

	/**
	 * Create an aliased <code>bibliotecapo.token</code> table reference
	 */
	public Token(java.lang.String alias) {
		super(alias, com.biblioteca.generatedclasses.Bibliotecapo.BIBLIOTECAPO, com.biblioteca.generatedclasses.tables.Token.TOKEN);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.biblioteca.generatedclasses.tables.records.TokenRecord, java.lang.Integer> getIdentity() {
		return com.biblioteca.generatedclasses.Keys.IDENTITY_TOKEN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.biblioteca.generatedclasses.tables.records.TokenRecord> getPrimaryKey() {
		return com.biblioteca.generatedclasses.Keys.KEY_TOKEN_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.biblioteca.generatedclasses.tables.records.TokenRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.biblioteca.generatedclasses.tables.records.TokenRecord>>asList(com.biblioteca.generatedclasses.Keys.KEY_TOKEN_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.biblioteca.generatedclasses.tables.Token as(java.lang.String alias) {
		return new com.biblioteca.generatedclasses.tables.Token(alias);
	}
}
