/**
 * This class is generated by jOOQ
 */
package com.biblioteca.generatedclasses.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Usuario extends org.jooq.impl.TableImpl<com.biblioteca.generatedclasses.tables.records.UsuarioRecord> {

	private static final long serialVersionUID = 1786215983;

	/**
	 * The singleton instance of <code>bibliotecapo.usuario</code>
	 */
	public static final com.biblioteca.generatedclasses.tables.Usuario USUARIO = new com.biblioteca.generatedclasses.tables.Usuario();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.biblioteca.generatedclasses.tables.records.UsuarioRecord> getRecordType() {
		return com.biblioteca.generatedclasses.tables.records.UsuarioRecord.class;
	}

	/**
	 * The column <code>bibliotecapo.usuario.id</code>. 
	 */
	public final org.jooq.TableField<com.biblioteca.generatedclasses.tables.records.UsuarioRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>bibliotecapo.usuario.usuario</code>. 
	 */
	public final org.jooq.TableField<com.biblioteca.generatedclasses.tables.records.UsuarioRecord, java.lang.String> USUARIO_ = createField("usuario", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this);

	/**
	 * The column <code>bibliotecapo.usuario.senha</code>. 
	 */
	public final org.jooq.TableField<com.biblioteca.generatedclasses.tables.records.UsuarioRecord, java.lang.String> SENHA = createField("senha", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this);

	/**
	 * The column <code>bibliotecapo.usuario.email</code>. 
	 */
	public final org.jooq.TableField<com.biblioteca.generatedclasses.tables.records.UsuarioRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this);

	/**
	 * The column <code>bibliotecapo.usuario.telefone</code>. 
	 */
	public final org.jooq.TableField<com.biblioteca.generatedclasses.tables.records.UsuarioRecord, java.lang.String> TELEFONE = createField("telefone", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this);

	/**
	 * The column <code>bibliotecapo.usuario.status_usuario</code>. 
	 */
	public final org.jooq.TableField<com.biblioteca.generatedclasses.tables.records.UsuarioRecord, java.lang.Integer> STATUS_USUARIO = createField("status_usuario", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>bibliotecapo.usuario.fk_perfil</code>. 
	 */
	public final org.jooq.TableField<com.biblioteca.generatedclasses.tables.records.UsuarioRecord, java.lang.Integer> FK_PERFIL = createField("fk_perfil", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * Create a <code>bibliotecapo.usuario</code> table reference
	 */
	public Usuario() {
		super("usuario", com.biblioteca.generatedclasses.Bibliotecapo.BIBLIOTECAPO);
	}

	/**
	 * Create an aliased <code>bibliotecapo.usuario</code> table reference
	 */
	public Usuario(java.lang.String alias) {
		super(alias, com.biblioteca.generatedclasses.Bibliotecapo.BIBLIOTECAPO, com.biblioteca.generatedclasses.tables.Usuario.USUARIO);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.biblioteca.generatedclasses.tables.records.UsuarioRecord, java.lang.Integer> getIdentity() {
		return com.biblioteca.generatedclasses.Keys.IDENTITY_USUARIO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.biblioteca.generatedclasses.tables.records.UsuarioRecord> getPrimaryKey() {
		return com.biblioteca.generatedclasses.Keys.KEY_USUARIO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.biblioteca.generatedclasses.tables.records.UsuarioRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.biblioteca.generatedclasses.tables.records.UsuarioRecord>>asList(com.biblioteca.generatedclasses.Keys.KEY_USUARIO_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.biblioteca.generatedclasses.tables.records.UsuarioRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.biblioteca.generatedclasses.tables.records.UsuarioRecord, ?>>asList(com.biblioteca.generatedclasses.Keys.USUARIO_IBFK_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.biblioteca.generatedclasses.tables.Usuario as(java.lang.String alias) {
		return new com.biblioteca.generatedclasses.tables.Usuario(alias);
	}
}
