/**
 * This class is generated by jOOQ
 */
package com.biblioteca.generatedclasses;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in bibliotecapo
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table bibliotecapo.autor
	 */
	public static final com.biblioteca.generatedclasses.tables.Autor AUTOR = com.biblioteca.generatedclasses.tables.Autor.AUTOR;

	/**
	 * The table bibliotecapo.emprestimo
	 */
	public static final com.biblioteca.generatedclasses.tables.Emprestimo EMPRESTIMO = com.biblioteca.generatedclasses.tables.Emprestimo.EMPRESTIMO;

	/**
	 * The table bibliotecapo.livro
	 */
	public static final com.biblioteca.generatedclasses.tables.Livro LIVRO = com.biblioteca.generatedclasses.tables.Livro.LIVRO;

	/**
	 * The table bibliotecapo.livro_autor
	 */
	public static final com.biblioteca.generatedclasses.tables.LivroAutor LIVRO_AUTOR = com.biblioteca.generatedclasses.tables.LivroAutor.LIVRO_AUTOR;

	/**
	 * The table bibliotecapo.multa
	 */
	public static final com.biblioteca.generatedclasses.tables.Multa MULTA = com.biblioteca.generatedclasses.tables.Multa.MULTA;

	/**
	 * The table bibliotecapo.perfil
	 */
	public static final com.biblioteca.generatedclasses.tables.Perfil PERFIL = com.biblioteca.generatedclasses.tables.Perfil.PERFIL;

	/**
	 * The table bibliotecapo.status_emprestimo
	 */
	public static final com.biblioteca.generatedclasses.tables.StatusEmprestimo STATUS_EMPRESTIMO = com.biblioteca.generatedclasses.tables.StatusEmprestimo.STATUS_EMPRESTIMO;

	/**
	 * The table bibliotecapo.token
	 */
	public static final com.biblioteca.generatedclasses.tables.Token TOKEN = com.biblioteca.generatedclasses.tables.Token.TOKEN;

	/**
	 * The table bibliotecapo.usuario
	 */
	public static final com.biblioteca.generatedclasses.tables.Usuario USUARIO = com.biblioteca.generatedclasses.tables.Usuario.USUARIO;
}
